### ISSUE TITLE
Override default classes for panels

### ISSUE THREAD

**Issue by pradyunsg** [executablebooks/sphinx-panels#39] opened 2020-09-18 10:52 UTC
**Is your feature request related to a problem? Please describe.**

I'd like to tweak how *all* panels are presented in my documentation. Specifically, I'd like to change the shadow that is used, to not be used.

**Describe the solution you'd like**

https://github.com/executablebooks/sphinx-panels/blob/d410fe3825761a6d1c596375e113902fec64dbc2/sphinx_panels/panels.py#L7-L9

Being able to pass them as values in conf.py would be great!

**Describe alternatives you've considered**

Patching the module in conf.py? That sounds horrible. :)

**Additional context**

Uhm... I'd like to change the default classes used, as described in https://sphinx-panels.readthedocs.io/en/latest/#components-panels, using conf.py for the entire documentation.

**Comment by chrisjsewell** [comment] 2020-10-03 06:13
Agree, but I'd say this is essentially a duplicate of #18

**Closed by chrisjsewell** 2020-10-03 06:13 UTC
Labels: enhancement
